AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: '-'
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ccbdha2lf1_p1
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./ccbdha2lf1
      Description: 'search'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-east-1:326453046054:function:ccbdha2lf1'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
